insert into public.albums (slug,title_en,title_vi,category_en,category_vi,description_en,description_vi,cover_image,is_published,sort_order) values
('a-love-letter-to-hoi-an','A Love Letter to Hội An','Thư tình gửi Hội An','Couples & Romance','Ảnh Cặp đôi','Managed Lookbook album.','Album Lookbook có thể chỉnh sửa.','https://drive.google.com/thumbnail?id=1noiT3J_eEyJ0oq0eKZkJLIvWRQAymPmP&sz=w1800',true,1),
('silk-and-lantern-light','Silk & Lantern Light','Lụa và ánh đèn lồng','Classic Áo Dài','Áo Dài truyền thống','Managed Lookbook album.','Album Lookbook có thể chỉnh sửa.','https://drive.google.com/thumbnail?id=1yRsPxrb7IYFqWF3v7rBqnYBhBI3JkExD&sz=w1800',true,2),
('together-here','Golden Hour in Hội An','Giờ vàng tại Hội An','Golden Hour & Rooftops','Hoàng hôn & Cafe Sân Thượng','Managed Lookbook album.','Album Lookbook có thể chỉnh sửa.','https://drive.google.com/thumbnail?id=1GG26n8q6gm79eoqi_gQxjqiQ_CSgKwyG&sz=w1800',true,3),
('historical-costumes','Historical Costumes','Việt Phục và Cổ Phục','Historical Costumes','Việt Phục/Cổ Phục','Managed Lookbook album.','Album Lookbook có thể chỉnh sửa.','https://drive.google.com/thumbnail?id=1UehLJlP41QZ8jWEKZmB3pSd-40nWXacq&sz=w1800',true,4),
('morning-serenity','Morning Serenity','Bình yên buổi sớm','Morning Serenity','Chụp sáng sớm','Managed Lookbook album.','Album Lookbook có thể chỉnh sửa.','https://drive.google.com/thumbnail?id=1nbFFjglGXLJ6jG12OQuzVn6k9uNkJDIG&sz=w1800',true,5),
('lantern-night-vibe','Lantern Night Vibe','Đêm Phố Cổ','Lantern Night Vibe','Đêm Phố Cổ','Managed Lookbook album.','Album Lookbook có thể chỉnh sửa.','https://drive.google.com/thumbnail?id=1tGiRFeJZGDPRWfIhmA6adibIkCmKgeci&sz=w1800',true,6),
('the-solo-muse','The Solo Muse','Chân dung Nàng thơ','The Solo Muse','Chân dung Nàng thơ','Managed Lookbook album.','Album Lookbook có thể chỉnh sửa.','https://drive.google.com/thumbnail?id=1gshAtbdPe3l7kM4YJSDuWrKC1Zx-fyDL&sz=w1800',true,7) on conflict(slug) do update set title_en=excluded.title_en,title_vi=excluded.title_vi,category_en=excluded.category_en,category_vi=excluded.category_vi,cover_image=excluded.cover_image,is_published=true,sort_order=excluded.sort_order,updated_at=now();
insert into public.album_photos (album_id,image_url,alt_en,alt_vi,sort_order) select * from (values ((select id from public.albums where slug='a-love-letter-to-hoi-an'),'https://drive.google.com/thumbnail?id=1noiT3J_eEyJ0oq0eKZkJLIvWRQAymPmP&sz=w1800','A Love Letter to Hội An · 1','',1),
((select id from public.albums where slug='a-love-letter-to-hoi-an'),'https://drive.google.com/thumbnail?id=1TiTTW7cKUJY5fGqA9CfeXTv3Ifsfmsyc&sz=w1800','A Love Letter to Hội An · 2','',2),
((select id from public.albums where slug='a-love-letter-to-hoi-an'),'https://drive.google.com/thumbnail?id=1WlIM1Zux3V-7U1YUoD3u4d_QQkkD_Wxf&sz=w1800','A Love Letter to Hội An · 3','',3),
((select id from public.albums where slug='a-love-letter-to-hoi-an'),'https://drive.google.com/thumbnail?id=1G0gxcMoCRpZfNbz7Xck8sZWwp88RjEbs&sz=w1800','A Love Letter to Hội An · 4','',4),
((select id from public.albums where slug='a-love-letter-to-hoi-an'),'https://drive.google.com/thumbnail?id=1ekp5mx8XKWmb5Wz-VJqYorr5EISDaFx8&sz=w1800','A Love Letter to Hội An · 5','',5),
((select id from public.albums where slug='a-love-letter-to-hoi-an'),'https://drive.google.com/thumbnail?id=1t2pJieBlw_UC-50BGRXofquVTpdBERuO&sz=w1800','A Love Letter to Hội An · 6','',6),
((select id from public.albums where slug='a-love-letter-to-hoi-an'),'https://drive.google.com/thumbnail?id=1WJjiyFTjtaSpeT1tkgvYK8mcUbFG_AMj&sz=w1800','A Love Letter to Hội An · 7','',7),
((select id from public.albums where slug='a-love-letter-to-hoi-an'),'https://drive.google.com/thumbnail?id=1AS0GF68BuQekY7tqv3ba7O_4lOr-yH1Q&sz=w1800','A Love Letter to Hội An · 8','',8),
((select id from public.albums where slug='a-love-letter-to-hoi-an'),'https://drive.google.com/thumbnail?id=1yG3G_TCEqLNAXKVDg1LZaC9ag9OfqvEM&sz=w1800','A Love Letter to Hội An · 9','',9),
((select id from public.albums where slug='a-love-letter-to-hoi-an'),'https://drive.google.com/thumbnail?id=1RCwa_9RQD8ZiGZnGxRdQGNSNpXY0hrIK&sz=w1800','A Love Letter to Hội An · 10','',10),
((select id from public.albums where slug='silk-and-lantern-light'),'https://drive.google.com/thumbnail?id=1yRsPxrb7IYFqWF3v7rBqnYBhBI3JkExD&sz=w1800','Silk & Lantern Light · 1','',1),
((select id from public.albums where slug='silk-and-lantern-light'),'https://drive.google.com/thumbnail?id=1f29Dm_MZD77N9dYRelw7pvYv8P7z7u9B&sz=w1800','Silk & Lantern Light · 2','',2),
((select id from public.albums where slug='silk-and-lantern-light'),'https://drive.google.com/thumbnail?id=1B_cFupHwAvaZobrJ18c2yfmBwip_ge8y&sz=w1800','Silk & Lantern Light · 3','',3),
((select id from public.albums where slug='silk-and-lantern-light'),'https://drive.google.com/thumbnail?id=1V0i-KzjRKRrnGV-uxbvDX4fAWzVRotG9&sz=w1800','Silk & Lantern Light · 4','',4),
((select id from public.albums where slug='silk-and-lantern-light'),'https://drive.google.com/thumbnail?id=1nbFFjglGXLJ6jG12OQuzVn6k9uNkJDIG&sz=w1800','Silk & Lantern Light · 5','',5),
((select id from public.albums where slug='silk-and-lantern-light'),'https://drive.google.com/thumbnail?id=1ZdBJxJkM7_cp8RMxPn2FfkgqhN1cCISV&sz=w1800','Silk & Lantern Light · 6','',6),
((select id from public.albums where slug='silk-and-lantern-light'),'https://drive.google.com/thumbnail?id=10yrQvjjE0njy7rnuHDsU0olzsIJ0eYGC&sz=w1800','Silk & Lantern Light · 7','',7),
((select id from public.albums where slug='silk-and-lantern-light'),'https://drive.google.com/thumbnail?id=1gshAtbdPe3l7kM4YJSDuWrKC1Zx-fyDL&sz=w1800','Silk & Lantern Light · 8','',8),
((select id from public.albums where slug='silk-and-lantern-light'),'https://drive.google.com/thumbnail?id=1axicRlja4yVvDXjzNI55NTAOWTTxrQjQ&sz=w1800','Silk & Lantern Light · 9','',9),
((select id from public.albums where slug='silk-and-lantern-light'),'https://drive.google.com/thumbnail?id=1ieREC7K0E2MI2sdiF6dcY5fhpxXsQLPg&sz=w1800','Silk & Lantern Light · 10','',10),
((select id from public.albums where slug='together-here'),'https://drive.google.com/thumbnail?id=1GG26n8q6gm79eoqi_gQxjqiQ_CSgKwyG&sz=w1800','Golden Hour in Hội An · 1','',1),
((select id from public.albums where slug='together-here'),'https://drive.google.com/thumbnail?id=1bfD3EF2te5TvKNy3aeElZZ0Edx06_Nr7&sz=w1800','Golden Hour in Hội An · 2','',2),
((select id from public.albums where slug='together-here'),'https://drive.google.com/thumbnail?id=1WeoCwRxxOOY0abIq1sOXi_I0LXfUAS2_&sz=w1800','Golden Hour in Hội An · 3','',3),
((select id from public.albums where slug='together-here'),'https://drive.google.com/thumbnail?id=1lCxmnGhTTBO4iIKDejoLrhqprTAs29YC&sz=w1800','Golden Hour in Hội An · 4','',4),
((select id from public.albums where slug='together-here'),'https://drive.google.com/thumbnail?id=1npnK0U_gw6lOa_ZhfAjydqrjGbQ9ahTn&sz=w1800','Golden Hour in Hội An · 5','',5),
((select id from public.albums where slug='together-here'),'https://drive.google.com/thumbnail?id=1mm_7SC4XAnXmgXu3X0rv-LJqDlRr2QeV&sz=w1800','Golden Hour in Hội An · 6','',6),
((select id from public.albums where slug='together-here'),'https://drive.google.com/thumbnail?id=1wVMU5EUq7o1j-lMSw3h01mkfmRTpcQft&sz=w1800','Golden Hour in Hội An · 7','',7),
((select id from public.albums where slug='together-here'),'https://drive.google.com/thumbnail?id=1XR_imB-ywdw4pvS4l1UKSmbRRBfp7CEm&sz=w1800','Golden Hour in Hội An · 8','',8),
((select id from public.albums where slug='together-here'),'https://drive.google.com/thumbnail?id=1bpSDYBPDaGoecABNCF6lkwRbwfn8Ccbm&sz=w1800','Golden Hour in Hội An · 9','',9),
((select id from public.albums where slug='together-here'),'https://drive.google.com/thumbnail?id=17qL7DDcS9Ks89elOpwaJAjheiYDroJyW&sz=w1800','Golden Hour in Hội An · 10','',10),
((select id from public.albums where slug='historical-costumes'),'https://drive.google.com/thumbnail?id=1UehLJlP41QZ8jWEKZmB3pSd-40nWXacq&sz=w1800','Historical Costumes · 1','',1),
((select id from public.albums where slug='historical-costumes'),'https://drive.google.com/thumbnail?id=1WEsT2ZUD_4DefbyEevCidRKeQyhJ298p&sz=w1800','Historical Costumes · 2','',2),
((select id from public.albums where slug='historical-costumes'),'https://drive.google.com/thumbnail?id=1uWwrKbvt1FPY1foCyr_cbXb5bCPSeqwR&sz=w1800','Historical Costumes · 3','',3),
((select id from public.albums where slug='historical-costumes'),'https://drive.google.com/thumbnail?id=1tGiRFeJZGDPRWfIhmA6adibIkCmKgeci&sz=w1800','Historical Costumes · 4','',4),
((select id from public.albums where slug='historical-costumes'),'https://drive.google.com/thumbnail?id=1_KI_g1mAWl6tAqOoWsCoaeRfvIksSksC&sz=w1800','Historical Costumes · 5','',5),
((select id from public.albums where slug='historical-costumes'),'https://drive.google.com/thumbnail?id=1iuzdVBr7UVr3-2Ts15XBPeWqBl64U4yB&sz=w1800','Historical Costumes · 6','',6),
((select id from public.albums where slug='historical-costumes'),'https://drive.google.com/thumbnail?id=15A2QvkEveAKik5UBKs2-v7PEJMpUysFt&sz=w1800','Historical Costumes · 7','',7),
((select id from public.albums where slug='historical-costumes'),'https://drive.google.com/thumbnail?id=143Fs6vWN1OiSMohIoIn-VAr--aXvQ7nO&sz=w1800','Historical Costumes · 8','',8),
((select id from public.albums where slug='historical-costumes'),'https://drive.google.com/thumbnail?id=1sPPPBMPxDgMZufDqMTn35RwJfvYt8aOm&sz=w1800','Historical Costumes · 9','',9),
((select id from public.albums where slug='historical-costumes'),'https://drive.google.com/thumbnail?id=1pQgaVEwIkvyFCO4Bz0W1-6U1SsVRI95F&sz=w1800','Historical Costumes · 10','',10),
((select id from public.albums where slug='morning-serenity'),'https://drive.google.com/thumbnail?id=1yRsPxrb7IYFqWF3v7rBqnYBhBI3JkExD&sz=w1800','Morning Serenity · 1','',1),
((select id from public.albums where slug='morning-serenity'),'https://drive.google.com/thumbnail?id=1f29Dm_MZD77N9dYRelw7pvYv8P7z7u9B&sz=w1800','Morning Serenity · 2','',2),
((select id from public.albums where slug='morning-serenity'),'https://drive.google.com/thumbnail?id=1B_cFupHwAvaZobrJ18c2yfmBwip_ge8y&sz=w1800','Morning Serenity · 3','',3),
((select id from public.albums where slug='morning-serenity'),'https://drive.google.com/thumbnail?id=1V0i-KzjRKRrnGV-uxbvDX4fAWzVRotG9&sz=w1800','Morning Serenity · 4','',4),
((select id from public.albums where slug='morning-serenity'),'https://drive.google.com/thumbnail?id=1nbFFjglGXLJ6jG12OQuzVn6k9uNkJDIG&sz=w1800','Morning Serenity · 5','',5),
((select id from public.albums where slug='morning-serenity'),'https://drive.google.com/thumbnail?id=1ZdBJxJkM7_cp8RMxPn2FfkgqhN1cCISV&sz=w1800','Morning Serenity · 6','',6),
((select id from public.albums where slug='morning-serenity'),'https://drive.google.com/thumbnail?id=10yrQvjjE0njy7rnuHDsU0olzsIJ0eYGC&sz=w1800','Morning Serenity · 7','',7),
((select id from public.albums where slug='morning-serenity'),'https://drive.google.com/thumbnail?id=1gshAtbdPe3l7kM4YJSDuWrKC1Zx-fyDL&sz=w1800','Morning Serenity · 8','',8),
((select id from public.albums where slug='morning-serenity'),'https://drive.google.com/thumbnail?id=1axicRlja4yVvDXjzNI55NTAOWTTxrQjQ&sz=w1800','Morning Serenity · 9','',9),
((select id from public.albums where slug='morning-serenity'),'https://drive.google.com/thumbnail?id=1ieREC7K0E2MI2sdiF6dcY5fhpxXsQLPg&sz=w1800','Morning Serenity · 10','',10),
((select id from public.albums where slug='lantern-night-vibe'),'https://drive.google.com/thumbnail?id=1UehLJlP41QZ8jWEKZmB3pSd-40nWXacq&sz=w1800','Lantern Night Vibe · 1','',1),
((select id from public.albums where slug='lantern-night-vibe'),'https://drive.google.com/thumbnail?id=1WEsT2ZUD_4DefbyEevCidRKeQyhJ298p&sz=w1800','Lantern Night Vibe · 2','',2),
((select id from public.albums where slug='lantern-night-vibe'),'https://drive.google.com/thumbnail?id=1uWwrKbvt1FPY1foCyr_cbXb5bCPSeqwR&sz=w1800','Lantern Night Vibe · 3','',3),
((select id from public.albums where slug='lantern-night-vibe'),'https://drive.google.com/thumbnail?id=1tGiRFeJZGDPRWfIhmA6adibIkCmKgeci&sz=w1800','Lantern Night Vibe · 4','',4),
((select id from public.albums where slug='lantern-night-vibe'),'https://drive.google.com/thumbnail?id=1_KI_g1mAWl6tAqOoWsCoaeRfvIksSksC&sz=w1800','Lantern Night Vibe · 5','',5),
((select id from public.albums where slug='lantern-night-vibe'),'https://drive.google.com/thumbnail?id=1iuzdVBr7UVr3-2Ts15XBPeWqBl64U4yB&sz=w1800','Lantern Night Vibe · 6','',6),
((select id from public.albums where slug='lantern-night-vibe'),'https://drive.google.com/thumbnail?id=15A2QvkEveAKik5UBKs2-v7PEJMpUysFt&sz=w1800','Lantern Night Vibe · 7','',7),
((select id from public.albums where slug='lantern-night-vibe'),'https://drive.google.com/thumbnail?id=143Fs6vWN1OiSMohIoIn-VAr--aXvQ7nO&sz=w1800','Lantern Night Vibe · 8','',8),
((select id from public.albums where slug='lantern-night-vibe'),'https://drive.google.com/thumbnail?id=1sPPPBMPxDgMZufDqMTn35RwJfvYt8aOm&sz=w1800','Lantern Night Vibe · 9','',9),
((select id from public.albums where slug='lantern-night-vibe'),'https://drive.google.com/thumbnail?id=1pQgaVEwIkvyFCO4Bz0W1-6U1SsVRI95F&sz=w1800','Lantern Night Vibe · 10','',10),
((select id from public.albums where slug='the-solo-muse'),'https://drive.google.com/thumbnail?id=1yRsPxrb7IYFqWF3v7rBqnYBhBI3JkExD&sz=w1800','The Solo Muse · 1','',1),
((select id from public.albums where slug='the-solo-muse'),'https://drive.google.com/thumbnail?id=1f29Dm_MZD77N9dYRelw7pvYv8P7z7u9B&sz=w1800','The Solo Muse · 2','',2),
((select id from public.albums where slug='the-solo-muse'),'https://drive.google.com/thumbnail?id=1B_cFupHwAvaZobrJ18c2yfmBwip_ge8y&sz=w1800','The Solo Muse · 3','',3),
((select id from public.albums where slug='the-solo-muse'),'https://drive.google.com/thumbnail?id=1V0i-KzjRKRrnGV-uxbvDX4fAWzVRotG9&sz=w1800','The Solo Muse · 4','',4),
((select id from public.albums where slug='the-solo-muse'),'https://drive.google.com/thumbnail?id=1nbFFjglGXLJ6jG12OQuzVn6k9uNkJDIG&sz=w1800','The Solo Muse · 5','',5),
((select id from public.albums where slug='the-solo-muse'),'https://drive.google.com/thumbnail?id=1ZdBJxJkM7_cp8RMxPn2FfkgqhN1cCISV&sz=w1800','The Solo Muse · 6','',6),
((select id from public.albums where slug='the-solo-muse'),'https://drive.google.com/thumbnail?id=10yrQvjjE0njy7rnuHDsU0olzsIJ0eYGC&sz=w1800','The Solo Muse · 7','',7),
((select id from public.albums where slug='the-solo-muse'),'https://drive.google.com/thumbnail?id=1gshAtbdPe3l7kM4YJSDuWrKC1Zx-fyDL&sz=w1800','The Solo Muse · 8','',8),
((select id from public.albums where slug='the-solo-muse'),'https://drive.google.com/thumbnail?id=1axicRlja4yVvDXjzNI55NTAOWTTxrQjQ&sz=w1800','The Solo Muse · 9','',9),
((select id from public.albums where slug='the-solo-muse'),'https://drive.google.com/thumbnail?id=1ieREC7K0E2MI2sdiF6dcY5fhpxXsQLPg&sz=w1800','The Solo Muse · 10','',10)) as seed(album_id,image_url,alt_en,alt_vi,sort_order) where not exists (select 1 from public.album_photos p where p.album_id=seed.album_id and p.image_url=seed.image_url);
