-- INHERE initial CMS content migration
-- Run after schema.sql. Safe to run again: records update by slug/key.

insert into public.page_content(page_key,title_en,title_vi,subtitle_en,subtitle_vi,body_en,body_vi,hero_image,sort_order)
values
('home','Your Story, Beautifully Told in Hội An','Câu chuyện của bạn, được kể thật đẹp tại Hội An','Ao Dai · Makeup · Photography','Áo dài · Trang điểm · Nhiếp ảnh','Premium photography, Vietnamese styling and carefully curated Hội An experiences for couples, solo travelers and families.','Trải nghiệm nhiếp ảnh cao cấp, phong cách Việt và hành trình Hội An được thiết kế riêng cho cặp đôi, khách cá nhân và gia đình.','https://images.unsplash.com/photo-1768017093068-7d0a34d0add0?auto=format&fit=crop&w=2560&q=94',0),
('services','Photography Experiences','Trải nghiệm chụp ảnh','Photography, designed around you','Nhiếp ảnh được thiết kế dành riêng cho bạn','Choose a quiet portrait, a romantic walk through the Old Town or an easy family experience.','Chọn chân dung nhẹ nhàng, buổi dạo phố lãng mạn hoặc trải nghiệm gia đình thoải mái.','https://images.unsplash.com/photo-1768017093154-1bfbaa3e3ccf?auto=format&fit=crop&w=1800&q=90',1),
('albums','Signature Albums','Album nổi bật','A living archive of Hội An','Kho lưu giữ những câu chuyện Hội An','Every album holds a different atmosphere, from quiet portraits to family journeys.','Mỗi album mang một bầu không khí riêng, từ chân dung yên bình đến hành trình gia đình.','https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1800&q=90',2),
('blog','The INHERE Journal','Nhật ký INHERE','Notes from the Old Town','Ghi chép từ Phố Cổ','Local light, thoughtful guides and visual ideas for experiencing Hội An beautifully.','Ánh sáng địa phương, hướng dẫn và ý tưởng hình ảnh để trải nghiệm Hội An thật đẹp.','https://images.unsplash.com/photo-1780803244219-a21588279fc6?auto=format&fit=crop&w=1800&q=90',3),
('about','The Art of Remembering','Nghệ thuật lưu giữ ký ức','The point of view behind INHERE','Góc nhìn phía sau INHERE','We photograph feeling, not performance.','Chúng tôi ghi lại cảm xúc, không phải sự trình diễn.','https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1800&q=90',4),
('contact','Let’s Create Together','Hãy cùng nhau sáng tạo','Start a conversation','Bắt đầu cuộc trò chuyện','Tell us what you want to remember and we will shape a personal plan for Hội An.','Hãy chia sẻ điều bạn muốn lưu giữ và chúng tôi sẽ tạo kế hoạch riêng tại Hội An.','https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1800&q=90',5)
on conflict(page_key) do update set title_en=excluded.title_en,title_vi=excluded.title_vi,subtitle_en=excluded.subtitle_en,subtitle_vi=excluded.subtitle_vi,body_en=excluded.body_en,body_vi=excluded.body_vi,hero_image=excluded.hero_image,updated_at=now();

insert into public.services(slug,title_en,title_vi,description_en,description_vi,image_url,price_label,sort_order)
values
('couple-photoshoot','Couple Photoshoot','Chụp ảnh cặp đôi','Celebrate your connection through romantic, natural photographs across Hội An’s most atmospheric locations.','Lưu giữ sự kết nối qua những bức ảnh lãng mạn và tự nhiên tại những địa điểm đẹp nhất Hội An.','https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1800&q=90','Contact for package details',1),
('solo-photoshoot','Solo Photoshoot','Chụp ảnh cá nhân','A personal portrait experience combining professional guidance, elegant styling and Hội An’s timeless character.','Trải nghiệm chân dung cá nhân kết hợp hướng dẫn chuyên nghiệp, phong cách thanh lịch và vẻ đẹp Hội An.','https://images.unsplash.com/photo-1768017093154-1bfbaa3e3ccf?auto=format&fit=crop&w=1800&q=90','Contact for package details',2),
('family-photoshoot','Family Photoshoot','Chụp ảnh gia đình','Relaxed, meaningful photographs created to preserve the warmth and personality of your family journey.','Những bức ảnh tự nhiên và ý nghĩa lưu giữ sự ấm áp trong hành trình gia đình.','https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1800&q=90','Contact for package details',3)
on conflict(slug) do update set title_en=excluded.title_en,title_vi=excluded.title_vi,description_en=excluded.description_en,description_vi=excluded.description_vi,image_url=excluded.image_url,price_label=excluded.price_label,sort_order=excluded.sort_order,updated_at=now();

insert into public.albums(slug,title_en,title_vi,category_en,category_vi,description_en,description_vi,cover_image,sort_order)
values
('a-love-letter-to-hoi-an','A Love Letter to Hội An','Lá thư tình gửi Hội An','Couple · Old Town','Cặp đôi · Phố Cổ','A romantic visual walk through the timeless streets of Hội An.','Hành trình hình ảnh lãng mạn qua những con phố cổ Hội An.','https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1800&q=90',1),
('silk-and-lantern-light','Silk & Lantern Light','Lụa và ánh đèn lồng','Ao Dai · Portrait','Áo dài · Chân dung','Vietnamese styling shaped by silk, color and warm lantern light.','Phong cách Việt được tạo nên từ lụa, màu sắc và ánh đèn lồng ấm áp.','https://images.unsplash.com/photo-1768017093154-1bfbaa3e3ccf?auto=format&fit=crop&w=1800&q=90',2),
('together-here','Together, Here','Bên nhau nơi đây','Family · Riverside','Gia đình · Bờ sông','Warm family moments by Hội An’s quiet riverside.','Khoảnh khắc gia đình ấm áp bên dòng sông Hội An.','https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1800&q=90',3),
('afterglow','Afterglow','Dư âm hoàng hôn','Golden Hour · Hội An','Giờ vàng · Hội An','Soft evening light, river reflections and the final warmth of day.','Ánh chiều dịu dàng, bóng nước và hơi ấm cuối ngày.','https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1800&q=90',4)
on conflict(slug) do update set title_en=excluded.title_en,title_vi=excluded.title_vi,category_en=excluded.category_en,category_vi=excluded.category_vi,description_en=excluded.description_en,description_vi=excluded.description_vi,cover_image=excluded.cover_image,sort_order=excluded.sort_order,updated_at=now();

insert into public.blog_posts(slug,title_en,title_vi,excerpt_en,excerpt_vi,content_en,content_vi,category_en,category_vi,cover_image,status,published_at)
values
('best-places-for-a-photoshoot-in-hoi-an','Best Places for a Photoshoot in Hội An','Những địa điểm chụp ảnh đẹp nhất Hội An','A thoughtful guide to beautiful corners, quieter streets and the changing light of the Old Town.','Hướng dẫn về những góc đẹp, con phố yên tĩnh và ánh sáng thay đổi của Phố Cổ.','Hội An changes character throughout the day. Early mornings feel intimate and quiet, while late afternoon brings warmth to ochre walls and river reflections.','Hội An thay đổi vẻ đẹp theo từng thời điểm trong ngày. Buổi sáng sớm yên bình, buổi chiều mang ánh sáng ấm áp lên những bức tường vàng và mặt sông.','Photography Locations','Địa điểm chụp ảnh','https://images.unsplash.com/photo-1780803244219-a21588279fc6?auto=format&fit=crop&w=1800&q=90','published',now()),
('what-to-wear-for-an-ao-dai-photoshoot','What to Wear for an Ao Dai Photoshoot','Mặc gì khi chụp ảnh Áo dài','How to choose color, silhouette and accessories that feel personal and photograph beautifully.','Cách chọn màu sắc, kiểu dáng và phụ kiện phù hợp để lên hình thật đẹp.','Choose an Ao Dai that allows comfortable movement and complements both your skin tone and the colors of Hội An.','Hãy chọn Áo dài thoải mái, phù hợp với màu da và sắc màu của Hội An.','Ao Dai','Áo dài','https://images.unsplash.com/photo-1768017093154-1bfbaa3e3ccf?auto=format&fit=crop&w=1800&q=90','published',now()),
('golden-hour-photography-in-hoi-an','Golden Hour Photography in Hội An','Chụp ảnh giờ vàng tại Hội An','Plan a relaxed session around soft riverside light and warm lantern-lit streets.','Lên kế hoạch cho buổi chụp nhẹ nhàng bên ánh sáng bờ sông và những con phố đèn lồng.','Golden hour brings gentle dimension to portraits and turns the Old Town into a warm, cinematic setting.','Giờ vàng tạo chiều sâu dịu dàng cho chân dung và biến Phố Cổ thành khung cảnh điện ảnh ấm áp.','Photoshoot Tips','Mẹo chụp ảnh','https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1800&q=90','published',now())
on conflict(slug) do update set title_en=excluded.title_en,title_vi=excluded.title_vi,excerpt_en=excluded.excerpt_en,excerpt_vi=excluded.excerpt_vi,content_en=excluded.content_en,content_vi=excluded.content_vi,category_en=excluded.category_en,category_vi=excluded.category_vi,cover_image=excluded.cover_image,status='published',published_at=coalesce(public.blog_posts.published_at,now()),updated_at=now();

insert into public.experiences(slug,title_en,title_vi,description_en,description_vi,category_en,category_vi,duration_label,price_label,image_url,sort_order)
values
('lantern-making-workshop','Lantern-Making Workshop','Workshop làm đèn lồng','A locally inspired workshop that complements your Hội An visit.','Workshop địa phương giúp hành trình Hội An thêm đáng nhớ.','Cultural Experience','Trải nghiệm văn hóa','Duration to be confirmed','Price to be confirmed','https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1800&q=90',1),
('riverside-evening-experience','Riverside Evening Experience','Trải nghiệm buổi tối bên sông','A relaxed evening shaped by river reflections and lantern-lit streets.','Buổi tối thư giãn bên bóng nước và những con phố đèn lồng.','Old Town Activity','Hoạt động Phố Cổ','Details to be confirmed','Price to be confirmed','https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1800&q=90',2),
('local-craft-experience','Local Craft Experience','Trải nghiệm thủ công địa phương','Discover local materials, techniques and a slower creative rhythm.','Khám phá vật liệu, kỹ thuật và nhịp sáng tạo địa phương.','Workshop','Workshop','Duration to be confirmed','Price to be confirmed','https://images.unsplash.com/photo-1509023464722-18d996393ca8?auto=format&fit=crop&w=1800&q=90',3)
on conflict(slug) do update set title_en=excluded.title_en,title_vi=excluded.title_vi,description_en=excluded.description_en,description_vi=excluded.description_vi,category_en=excluded.category_en,category_vi=excluded.category_vi,duration_label=excluded.duration_label,price_label=excluded.price_label,image_url=excluded.image_url,sort_order=excluded.sort_order,updated_at=now();

insert into public.rentals(slug,type,title_en,title_vi,description_en,description_vi,image_url,price_label,sort_order)
values
('outfits','outfit','Ao Dai Collection','Bộ sưu tập Áo dài','Elegant silhouettes and colors selected for portrait sessions across Hội An.','Kiểu dáng thanh lịch và màu sắc được chọn cho buổi chụp tại Hội An.','https://images.unsplash.com/photo-1768017093154-1bfbaa3e3ccf?auto=format&fit=crop&w=1800&q=90','Ask for availability',1),
('accessories','accessory','Accessories & Finishing','Phụ kiện và hoàn thiện','Headpieces, fans and considered details that complete your visual story.','Mấn, quạt và những chi tiết hoàn thiện câu chuyện hình ảnh.','https://images.unsplash.com/photo-1509023464722-18d996393ca8?auto=format&fit=crop&w=1800&q=90','Ask for availability',2)
on conflict(slug) do update set type=excluded.type,title_en=excluded.title_en,title_vi=excluded.title_vi,description_en=excluded.description_en,description_vi=excluded.description_vi,image_url=excluded.image_url,price_label=excluded.price_label,sort_order=excluded.sort_order,updated_at=now();

insert into public.testimonials(quote_en,quote_vi,author_name,author_title_en,author_title_vi,avatar_url,rating,sort_order)
select * from (values
('The whole experience felt calm and personal. We stopped posing and simply enjoyed Hội An together.','Trải nghiệm thật nhẹ nhàng và riêng tư. Chúng tôi không còn tạo dáng mà chỉ tận hưởng Hội An bên nhau.','Sophie & Daniel','Couple experience · Guest story','Trải nghiệm cặp đôi · Câu chuyện khách hàng','https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=85',5,1),
('I arrived nervous and left feeling completely confident. The styling and gentle direction were wonderful.','Tôi đến với chút lo lắng nhưng ra về đầy tự tin. Phong cách và sự hướng dẫn thật tuyệt vời.','Mina K.','Solo portrait · Guest story','Chân dung cá nhân · Câu chuyện khách hàng','https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=85',5,2),
('Our children could be themselves, and the photographs genuinely feel like our family.','Các con được là chính mình và những bức ảnh thật sự mang đúng cảm xúc gia đình.','The Nguyen Family','Family session · Guest story','Buổi chụp gia đình · Câu chuyện khách hàng','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=85',5,3)
) as seed(quote_en,quote_vi,author_name,author_title_en,author_title_vi,avatar_url,rating,sort_order)
where not exists (select 1 from public.testimonials);
